"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type SearchResult={id:string;label:string;meta?:string};

export default function DocumentRelationshipsManager({documentId,relationships}:any){
  const router=useRouter(); const [error,setError]=useState(""); const [targetType,setTargetType]=useState("document"); const [query,setQuery]=useState(""); const [results,setResults]=useState<SearchResult[]>([]); const [selected,setSelected]=useState<SearchResult|null>(null); const [saving,setSaving]=useState(false);
  const searchable=["document","law","institution"].includes(targetType);

  useEffect(()=>{setSelected(null);setResults([]);setQuery("");},[targetType]);
  async function search(){setError(""); if(query.trim().length<2)return setResults([]); const res=await fetch(`/api/admin/documents/search-targets?type=${encodeURIComponent(targetType)}&q=${encodeURIComponent(query.trim())}`); const json=await res.json(); if(!res.ok)return setError(json.error||"Search failed"); setResults(json.results||[]);}
  async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const form=new FormData(e.currentTarget);const targetId=searchable?selected?.id:String(form.get("manual_target_id")||"").trim(); if(!targetId){setSaving(false);return setError("Choose or enter a target.");} const body={target_type:targetType,target_id:targetId,relationship_type:form.get("relationship_type"),description:form.get("description"),verification_status:form.get("verification_status")}; const res=await fetch(`/api/admin/documents/${documentId}/relationships`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const json=await res.json();setSaving(false);if(!res.ok)return setError(json.error||"Could not add relationship");setSelected(null);setResults([]);setQuery("");router.refresh();}
  async function remove(id:string){if(!window.confirm("Remove this relationship?"))return;const res=await fetch(`/api/admin/documents/${documentId}/relationships?relationshipId=${encodeURIComponent(id)}`,{method:"DELETE"});const json=await res.json();if(!res.ok)return setError(json.error||"Could not remove relationship");router.refresh();}
  return <>
    {error&&<div className="govuk-error-summary" role="alert"><div className="govuk-error-summary__body">{error}</div></div>}
    <h2 className="govuk-heading-l">Relationships</h2>
    {relationships.length===0?<p className="govuk-body">No relationships recorded.</p>:<div className="govuk-table__container"><table className="govuk-table"><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header">Relationship</th><th className="govuk-table__header">Target</th><th className="govuk-table__header">Verification</th><th className="govuk-table__header">Description</th><th className="govuk-table__header"><span className="govuk-visually-hidden">Actions</span></th></tr></thead><tbody className="govuk-table__body">{relationships.map((r:any)=><tr key={r.id} className="govuk-table__row"><td className="govuk-table__cell">{r.relationship_type}</td><td className="govuk-table__cell"><strong>{r.targetType}</strong><br/>{r.targetLabel}</td><td className="govuk-table__cell">{r.verification_status}</td><td className="govuk-table__cell">{r.description||"—"}</td><td className="govuk-table__cell"><button type="button" className="govuk-button govuk-button--warning govuk-button--small" onClick={()=>remove(r.id)}>Remove</button></td></tr>)}</tbody></table></div>}

    <h2 className="govuk-heading-l govuk-!-margin-top-8">Add relationship</h2>
    <form onSubmit={add}>
      <div className="govuk-form-group"><label className="govuk-label" htmlFor="target_type">Target type</label><select className="govuk-select" id="target_type" value={targetType} onChange={e=>setTargetType(e.target.value)}><option value="document">Another document</option><option value="law">Law / Constitution document</option><option value="institution">Institution</option><option value="provision">Legal provision UUID</option><option value="gazette">Gazette record UUID</option></select></div>
      {searchable?<div className="govuk-form-group"><label className="govuk-label" htmlFor="target_search">Find target</label><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input className="govuk-input govuk-!-width-two-thirds" id="target_search" value={query} onChange={e=>setQuery(e.target.value)}/><button className="govuk-button govuk-button--secondary" type="button" onClick={search}>Search</button></div>{results.length>0?<div className="govuk-radios govuk-!-margin-top-3">{results.map(r=><div className="govuk-radios__item" key={r.id}><input className="govuk-radios__input" type="radio" name="target_result" id={`target-${r.id}`} checked={selected?.id===r.id} onChange={()=>setSelected(r)}/><label className="govuk-label govuk-radios__label" htmlFor={`target-${r.id}`}>{r.label}{r.meta?<span className="govuk-hint">{r.meta}</span>:null}</label></div>)}</div>:null}</div>:<div className="govuk-form-group"><label className="govuk-label" htmlFor="manual_target_id">Target UUID</label><span className="govuk-hint">For Gazette and legal-provision targets, enter the record UUID until those modules expose a shared target-search API.</span><input className="govuk-input" id="manual_target_id" name="manual_target_id" /></div>}
      <div className="govuk-form-group"><label className="govuk-label" htmlFor="relationship_type">Relationship</label><select className="govuk-select" id="relationship_type" name="relationship_type">{["related_to","supersedes","revises","replaces","implements","supports","references","part_of","responds_to","based_on"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></div>
      <div className="govuk-form-group"><label className="govuk-label" htmlFor="description">Description</label><textarea className="govuk-textarea" id="description" name="description" rows={3}/></div>
      <div className="govuk-form-group"><label className="govuk-label" htmlFor="verification_status">Verification</label><select className="govuk-select" id="verification_status" name="verification_status"><option>Pending</option><option>Verified</option><option>Rejected</option></select></div>
      <button className="govuk-button" disabled={saving}>{saving?"Saving…":"Add relationship"}</button>
    </form>
  </>;
}
