import type { LinkPhrase } from "@/lib/constitution/link-phrases";

/**
 * Curated starter glossary. Paths match public CitizenGuide routes.
 * Admins can edit/disable in the Link phrases tab after seeding.
 */
export const SEED_LINK_PHRASES: Omit<LinkPhrase, "_id">[] = [
  {
    phrase: "National Assembly",
    matchMode: "caseInsensitive",
    internalHref: "/government/legislature/national-assembly/members",
    externalHref: "https://www.parliament.go.ke/",
    externalLabel: "Parliament of Kenya",
    sortOrder: 10,
    enabled: true,
  },
  {
    phrase: "the Senate",
    matchMode: "caseInsensitive",
    internalHref: "/government/legislature/senate",
    externalHref: "https://www.parliament.go.ke/",
    externalLabel: "Parliament of Kenya",
    sortOrder: 20,
    enabled: true,
  },
  {
    phrase: "Senate",
    matchMode: "caseInsensitive",
    internalHref: "/government/legislature/senate",
    externalHref: "https://www.parliament.go.ke/",
    externalLabel: "Parliament of Kenya",
    sortOrder: 21,
    enabled: true,
  },
  {
    phrase: "Parliament",
    matchMode: "caseInsensitive",
    internalHref: "/government/legislature",
    externalHref: "https://www.parliament.go.ke/",
    externalLabel: "Parliament of Kenya",
    sortOrder: 30,
    enabled: true,
  },
  {
    phrase: "Independent Electoral and Boundaries Commission",
    matchMode: "caseInsensitive",
    internalHref: "/government/institutions",
    externalHref: "https://www.iebc.or.ke/",
    externalLabel: "IEBC",
    sortOrder: 5,
    enabled: true,
  },
  {
    phrase: "IEBC",
    matchMode: "exact",
    internalHref: "/government/institutions",
    externalHref: "https://www.iebc.or.ke/",
    externalLabel: "IEBC",
    sortOrder: 6,
    enabled: true,
  },
  {
    phrase: "Judiciary",
    matchMode: "caseInsensitive",
    internalHref: "/constitution/chapter/10",
    externalHref: "https://www.judiciary.go.ke/",
    externalLabel: "Judiciary of Kenya",
    sortOrder: 40,
    enabled: true,
  },
  {
    phrase: "Chief Justice",
    matchMode: "caseInsensitive",
    internalHref: "/constitution/chapter/10",
    externalHref: "https://www.judiciary.go.ke/",
    externalLabel: "Judiciary of Kenya",
    sortOrder: 41,
    enabled: true,
  },
  {
    phrase: "Cabinet Secretary",
    matchMode: "caseInsensitive",
    internalHref: "/government/cabinet",
    sortOrder: 50,
    enabled: true,
  },
  {
    phrase: "President",
    matchMode: "caseInsensitive",
    internalHref: "/constitution/chapter/9",
    externalHref: "https://www.president.go.ke/",
    externalLabel: "Presidency",
    sortOrder: 60,
    enabled: true,
  },
  {
    phrase: "Deputy President",
    matchMode: "caseInsensitive",
    internalHref: "/constitution/chapter/9",
    sortOrder: 61,
    enabled: true,
  },
  {
    phrase: "county assembly",
    matchMode: "caseInsensitive",
    internalHref: "/government/county-assemblies/mcas",
    sortOrder: 70,
    enabled: true,
  },
  {
    phrase: "Bill of Rights",
    matchMode: "caseInsensitive",
    constitutionChapter: 4,
    sortOrder: 8,
    enabled: true,
  },
];
